
import { ChangeDetectionStrategy, Component } from '@angular/core';

@Component({
  selector: 'app-disclaimer',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="prose prose-invert max-w-none animate-fade-in">
      <h1>Disclaimer</h1>
      <p>Last updated: July 25, 2024</p>
      
      <h2>General Information</h2>
      <p>The information contained on the Service is for general information purposes only. The Company assumes no responsibility for errors or omissions in the contents of the Service.</p>

      <h2>No Professional Advice</h2>
      <p>The Service offers information and is designed for educational purposes only. This information is not a substitute for, and does not replace, professional SEO or business advice. The use of any information provided on this Service is solely at your own risk.</p>
      
      <h2>External Links Disclaimer</h2>
      <p>The Service may contain links to external websites that are not provided or maintained by or in any way affiliated with the Company. Please note that the Company does not guarantee the accuracy, relevance, timeliness, or completeness of any information on these external websites.</p>
      
      <h2>Views Expressed Disclaimer</h2>
      <p>The information generated by the AI is based on patterns in data and does not represent the views or opinions of the Company.</p>
    </div>
    <style>
        .prose h1 { @apply text-3xl font-bold mb-4 text-slate-100; }
        .prose h2 { @apply text-2xl font-bold mt-6 mb-3 text-slate-200; }
        .prose p { @apply mb-4 text-slate-400; }
        @keyframes fade-in { from { opacity: 0; } to { opacity: 1; } }
        .animate-fade-in { animation: fade-in 0.5s ease-out; }
    </style>
  `
})
export class DisclaimerComponent {}
